### ISSUE TITLE
Tests Break

### ISSUE THREAD

**Issue by Bombe** [freenet/fred#310]
Freenet’s tests don’t run on my build server.

```
00:00:53.260     [junit] Testcase: testSmallSplitfileChooseCooldownNotRNF took 0.017 sec
00:00:53.260     [junit] Testcase: testPersistentSmallSplitfileNoLastBlockCompletion took 0.019 sec
00:00:53.260     [junit] Testcase: testSmallSplitfileChooseCompletion took 0.017 sec
00:00:53.260     [junit] Testcase: testSmallSplitfileConsecutiveRNFsHack took 0.015 sec
00:00:53.260     [junit] Testcase: testCancelAlt took 0.103 sec
00:00:53.260     [junit] 	FAILED
00:00:53.260     [junit] null
00:00:53.260     [junit] junit.framework.AssertionFailedError
00:00:53.260     [junit] 	at freenet.client.async.SplitFileInserterStorageTest.testCancelAlt(SplitFileInserterStorageTest.java:1396)
00:00:53.260     [junit] 	at freenet.client.async.SplitFileInserterStorageTest.testCancelAlt(SplitFileInserterStorageTest.java:1360)
00:00:53.260     [junit] 
00:00:53.263 
00:00:53.263 BUILD FAILED
00:00:53.263 /var/lib/jenkins/jobs/Freenet/workspace/build-clean.xml:326: Test freenet.client.async.SplitFileInserterStorageTest failed
```

Involved versions: Fred 0de9f1fdb99849776286690e1db3aa83fc17e34e, Java 1.7.0_72-b14 on Ubuntu 14.04.1/x86_64, JUnit 4.11, BouncyCastle 1.51.

**Comment by llamora** [comment]
This test also fails with BouncyCastle 1.52.0.6 on Ubuntu 14.10

**Comment by xor-freenet** [comment]
This bugtracker is not used. Please continue the discussion in the official bugtracker: https://bugs.freenetproject.org/view.php?id=6459
